// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvlZ3oCfm_JUs2ijmxN4nbGMtwA0FAb8',
    appId: '1:999701990661:web:1e67307604fd858e7e3b6c',
    messagingSenderId: '999701990661',
    projectId: 'realestateinsignia',
    authDomain: 'realestateinsignia.firebaseapp.com',
    storageBucket: 'realestateinsignia.appspot.com',
    measurementId: 'G-R2640F8HH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFdUDk-BZVdsFX9fHtrRPmiDMSDkUD1w',
    appId: '1:999701990661:android:307e1036ce39e0167e3b6c',
    messagingSenderId: '999701990661',
    projectId: 'realestateinsignia',
    storageBucket: 'realestateinsignia.appspot.com',
  );
}
